import "./divisao.scss";

function Divisao() {
  return (
    <section className="divisao">
      <h2>
        AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO • AUMENTE SEU FATURAMENTO •
      </h2>
    </section>
  );
}

export default Divisao;
